In [ ]:
!pip install numpy

In [20]:
import numpy as np

In [ ]:
## Why NuMpy?

- Mathematical and logical operations on **arrays**.

- Efficient storage and manipulation of **numerical arrays** is which is fundamental in  the process of  **data science**.

- NumPy arrays form the core of nearly the entire **ecosystem** of **data science** tools in Python,

In [2]:
import time as tm

size_1 = 1000000

def pure_python_version():
    start_time_pp =  tm.time() ## time of start of code execution
    list1 = range(size_1)
    list2 = range(size_1)
    sum_list=[list1[i]+list2[i] for i in range(len(list1))]
    end_time_pp =  tm.time()
    return end_time_pp - start_time_pp ## end time for execution (difference)

def numpy_version():
    start_time_np = tm.time()
    array1 = np.arange(size_1)
    array2 =  np.arange(size_1)
    sum_array = array1 + array2
    end_time_np = tm.time()
    return end_time_np - start_time_np ## end time for execution (difference)

python_time = pure_python_version()
numpy_time  = numpy_version()

print("pure python version=",python_time)
print("numpy =",numpy_time)

pure python version= 0.4732217788696289
numpy = 0.009211063385009766


In [3]:
my_list=[2,3,4,6,7,8]

In [4]:
type(my_list)

list

In [5]:
aar =np.array(my_list)

In [7]:
type(aar)

numpy.ndarray

In [8]:
aar.ndim

1

In [22]:
array_2 = [[1,2,3],[4,5,6],[7,8,9]]
array_3= np.array(array_2)
array_3
type(array_3)

numpy.ndarray

In [24]:
type(array_2)

list

In [25]:
array_3.ndim

2

In [26]:
array_3.shape

(3, 3)

In [27]:
a = np.array([1, 2, 3,7,5,1], ndmin = 12) 
print (a)
np.ndim(a)

[[[[[[[[[[[[1 2 3 7 5 1]]]]]]]]]]]]


12

In [28]:
a = np.array([1, 2, 3, 4], dtype = complex) 
print (a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [29]:
len(array_3)

3

In [30]:
array_3[2] 

array([7, 8, 9])

In [31]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
array_3[:,1]

array([2, 5, 8])

In [33]:
array_3[:1,1]

array([2])

In [34]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [37]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [38]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [39]:
np.eye(3,3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [43]:
np.linspace(-20,-15,10)

array([-20.        , -19.44444444, -18.88888889, -18.33333333,
       -17.77777778, -17.22222222, -16.66666667, -16.11111111,
       -15.55555556, -15.        ])

In [44]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
array_3.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [46]:
x=[[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]]
x=np.array(x)
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [47]:
x.reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 4,  5],
       [ 6,  7],
       [ 7,  8],
       [ 9, 10],
       [10, 11],
       [12, 13]])

In [48]:
x.min()

1

In [49]:
x.max()

13

In [50]:
x.sum()

112

In [52]:
x.mean()

7.0

In [54]:
x.std()

3.5355339059327378

In [55]:
x.var()

12.5

In [56]:
x.min(axis=0)

array([1, 2, 3, 4])

In [57]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [58]:
x.min(axis=1)

array([ 1,  4,  7, 10])

In [59]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [60]:
x.flatten()

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10, 10, 11, 12, 13])

In [61]:
x.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12],
       [ 4,  7, 10, 13]])

In [69]:
A = np.array([ [4, 10, 11], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))
print(A)

[[ 4 10 11]
 [21 22 23]
 [31 32 33]]


In [70]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [71]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
A+B

array([[ 5., 11., 12.],
       [22., 23., 24.],
       [32., 33., 34.]])

In [73]:
A-B

array([[ 3.,  9., 10.],
       [20., 21., 22.],
       [30., 31., 32.]])

In [74]:
A/B

array([[ 4., 10., 11.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [75]:
B-A

array([[ -3.,  -9., -10.],
       [-20., -21., -22.],
       [-30., -31., -32.]])

In [76]:
A*B

array([[ 4., 10., 11.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [77]:
A%3

array([[1, 1, 2],
       [0, 1, 2],
       [1, 2, 0]], dtype=int32)

In [78]:
np.dot(A,B)

array([[25., 25., 25.],
       [66., 66., 66.],
       [96., 96., 96.]])

In [79]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [80]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [81]:
np.sqrt(A)

array([[2.        , 3.16227766, 3.31662479],
       [4.58257569, 4.69041576, 4.79583152],
       [5.56776436, 5.65685425, 5.74456265]])

In [82]:
np.exp(A)

array([[5.45981500e+01, 2.20264658e+04, 5.98741417e+04],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09],
       [2.90488497e+13, 7.89629602e+13, 2.14643580e+14]])

In [83]:
np.log(A)

array([[1.38629436, 2.30258509, 2.39789527],
       [3.04452244, 3.09104245, 3.13549422],
       [3.4339872 , 3.4657359 , 3.49650756]])

In [85]:
a=np.array([[11.667,23.662],[33.21,45.887]])

In [86]:
a

array([[11.667, 23.662],
       [33.21 , 45.887]])

In [87]:
np.around(a)

array([[12., 24.],
       [33., 46.]])

In [88]:
np.around(a, decimals=2)

array([[11.67, 23.66],
       [33.21, 45.89]])

In [89]:
np.concatenate([A,B])

array([[ 4., 10., 11.],
       [21., 22., 23.],
       [31., 32., 33.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [90]:
np.random.randint(2,5,(3,3))

array([[4, 2, 3],
       [2, 2, 3],
       [4, 3, 4]])

In [91]:
np.random.rand(5,4)

array([[0.44503466, 0.25528205, 0.15178325, 0.1907589 ],
       [0.89778629, 0.85899406, 0.65016077, 0.50698309],
       [0.15103159, 0.60251906, 0.85073776, 0.98028795],
       [0.49349914, 0.58870283, 0.89543049, 0.26109557],
       [0.78621998, 0.7659007 , 0.56974845, 0.24618355]])

In [92]:
np.random.randn(5,4)

array([[-1.18484906, -1.00655306,  1.548347  ,  0.51806924],
       [ 0.80409303,  1.22839439,  1.14051675,  1.44703431],
       [ 1.23654372, -1.37469015,  0.52238786, -0.06056945],
       [ 1.22074766, -0.33336444, -1.03380499,  0.44915244],
       [-1.05393658, -0.9693018 ,  0.30703316, -0.6069578 ]])

In [93]:
np.nan

nan